services:
  - type: web
    name: truth-dare-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: CHAT_ID
        value: -1002315817553
